# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/sf_Ubuntu_Shared/MyGitHub/treasy

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/sf_Ubuntu_Shared/MyGitHub/treasy

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/sf_Ubuntu_Shared/MyGitHub/treasy/CMakeFiles /media/sf_Ubuntu_Shared/MyGitHub/treasy/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/sf_Ubuntu_Shared/MyGitHub/treasy/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named treasyLib

# Build rule for target.
treasyLib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 treasyLib
.PHONY : treasyLib

# fast build rule for target.
treasyLib/fast:
	$(MAKE) -f CMakeFiles/treasyLib.dir/build.make CMakeFiles/treasyLib.dir/build
.PHONY : treasyLib/fast

#=============================================================================
# Target rules for targets named treasy

# Build rule for target.
treasy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 treasy
.PHONY : treasy

# fast build rule for target.
treasy/fast:
	$(MAKE) -f CMakeFiles/treasy.dir/build.make CMakeFiles/treasy.dir/build
.PHONY : treasy/fast

# Manual pre-install relink rule for target.
treasy/preinstall:
	$(MAKE) -f CMakeFiles/treasy.dir/build.make CMakeFiles/treasy.dir/preinstall
.PHONY : treasy/preinstall

src/error.o: src/error.cpp.o

.PHONY : src/error.o

# target to build an object file
src/error.cpp.o:
	$(MAKE) -f CMakeFiles/treasyLib.dir/build.make CMakeFiles/treasyLib.dir/src/error.cpp.o
.PHONY : src/error.cpp.o

src/error.i: src/error.cpp.i

.PHONY : src/error.i

# target to preprocess a source file
src/error.cpp.i:
	$(MAKE) -f CMakeFiles/treasyLib.dir/build.make CMakeFiles/treasyLib.dir/src/error.cpp.i
.PHONY : src/error.cpp.i

src/error.s: src/error.cpp.s

.PHONY : src/error.s

# target to generate assembly for a file
src/error.cpp.s:
	$(MAKE) -f CMakeFiles/treasyLib.dir/build.make CMakeFiles/treasyLib.dir/src/error.cpp.s
.PHONY : src/error.cpp.s

src/extension_finder.o: src/extension_finder.cpp.o

.PHONY : src/extension_finder.o

# target to build an object file
src/extension_finder.cpp.o:
	$(MAKE) -f CMakeFiles/treasyLib.dir/build.make CMakeFiles/treasyLib.dir/src/extension_finder.cpp.o
.PHONY : src/extension_finder.cpp.o

src/extension_finder.i: src/extension_finder.cpp.i

.PHONY : src/extension_finder.i

# target to preprocess a source file
src/extension_finder.cpp.i:
	$(MAKE) -f CMakeFiles/treasyLib.dir/build.make CMakeFiles/treasyLib.dir/src/extension_finder.cpp.i
.PHONY : src/extension_finder.cpp.i

src/extension_finder.s: src/extension_finder.cpp.s

.PHONY : src/extension_finder.s

# target to generate assembly for a file
src/extension_finder.cpp.s:
	$(MAKE) -f CMakeFiles/treasyLib.dir/build.make CMakeFiles/treasyLib.dir/src/extension_finder.cpp.s
.PHONY : src/extension_finder.cpp.s

src/help.o: src/help.cpp.o

.PHONY : src/help.o

# target to build an object file
src/help.cpp.o:
	$(MAKE) -f CMakeFiles/treasyLib.dir/build.make CMakeFiles/treasyLib.dir/src/help.cpp.o
.PHONY : src/help.cpp.o

src/help.i: src/help.cpp.i

.PHONY : src/help.i

# target to preprocess a source file
src/help.cpp.i:
	$(MAKE) -f CMakeFiles/treasyLib.dir/build.make CMakeFiles/treasyLib.dir/src/help.cpp.i
.PHONY : src/help.cpp.i

src/help.s: src/help.cpp.s

.PHONY : src/help.s

# target to generate assembly for a file
src/help.cpp.s:
	$(MAKE) -f CMakeFiles/treasyLib.dir/build.make CMakeFiles/treasyLib.dir/src/help.cpp.s
.PHONY : src/help.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/treasy.dir/build.make CMakeFiles/treasy.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/treasy.dir/build.make CMakeFiles/treasy.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/treasy.dir/build.make CMakeFiles/treasy.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/treasy.o: src/treasy.cpp.o

.PHONY : src/treasy.o

# target to build an object file
src/treasy.cpp.o:
	$(MAKE) -f CMakeFiles/treasyLib.dir/build.make CMakeFiles/treasyLib.dir/src/treasy.cpp.o
.PHONY : src/treasy.cpp.o

src/treasy.i: src/treasy.cpp.i

.PHONY : src/treasy.i

# target to preprocess a source file
src/treasy.cpp.i:
	$(MAKE) -f CMakeFiles/treasyLib.dir/build.make CMakeFiles/treasyLib.dir/src/treasy.cpp.i
.PHONY : src/treasy.cpp.i

src/treasy.s: src/treasy.cpp.s

.PHONY : src/treasy.s

# target to generate assembly for a file
src/treasy.cpp.s:
	$(MAKE) -f CMakeFiles/treasyLib.dir/build.make CMakeFiles/treasyLib.dir/src/treasy.cpp.s
.PHONY : src/treasy.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... treasyLib"
	@echo "... treasy"
	@echo "... install/local"
	@echo "... edit_cache"
	@echo "... src/error.o"
	@echo "... src/error.i"
	@echo "... src/error.s"
	@echo "... src/extension_finder.o"
	@echo "... src/extension_finder.i"
	@echo "... src/extension_finder.s"
	@echo "... src/help.o"
	@echo "... src/help.i"
	@echo "... src/help.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/treasy.o"
	@echo "... src/treasy.i"
	@echo "... src/treasy.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

